vich_uploader:
    db_driver: orm

    mappings:
        loans:
            uri_prefix: '%app.path.loan_files%'
            upload_destination: '%kernel.project_dir%/public%app.path.loan_files%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
